- name: 🔍 Debug Google Credentials Raw
  env:
    GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  run: |
    echo "=== GOOGLE CREDENTIALS DEBUG ==="
    echo "Length: ${#GOOGLE_CREDENTIALS}"
    echo "First 200 chars: ${GOOGLE_CREDENTIALS:0:200}"
    echo "Last 200 chars: ${GOOGLE_CREDENTIALS: -200}"
    echo ""

    # Try to parse as JSON
    if echo "$GOOGLE_CREDENTIALS" | jq . > /dev/null 2>&1; then
      echo "✅ Valid JSON detected"
      echo "client_email: $(echo "$GOOGLE_CREDENTIALS" | jq -r '.client_email // "MISSING"')"
      echo "project_id: $(echo "$GOOGLE_CREDENTIALS" | jq -r '.project_id // "MISSING"')"
    else
      echo "❌ Invalid JSON format"
      echo "Attempting to detect
